project:
  type: website
  output-dir: docs

website:
  title: "Parker Neal"
  navbar:
    left:
      - href: index.qmd
        text: About
      - experience.qmd
      - interest.qmd

format:
  html:
    page-layout: full
    theme: 
      light: yeti
      dark: vapor
    css: styles.css
    toc: false

editor: visual

