---
title: "Experience"
author: ""
---

**Personal Shopper**

*Instacart \| Fort Collins, Colorado* Winter 2022 to Present

-   Cultivated a fast-paced work ethic, managing multiple orders and meeting tight deadlines and expectations

-   Strengthened critical thinking skills by offering creative substitutions and addressing customer concerns professionally

-   Delivered exceptional customer service by maintaining clear communication to ensure customer was satisfied

**Study Abroad Field Researcher**

*SIT Panama: Tropical Ecology and Conservation \| Panama* Winter 2024 to Summer 2024

-   Conducted ecological field studies focusing on tropical biodiversity and conservation

-   Designed and executed independent marine research in collaboration with local experts

-   Gained hands-on experience in community-based conservation initiatives

**Wildland Fire and Fuels Technician**

*CSU Department of Forest and Rangeland Stewardship \| Fort Collins, Colorado* Summer 2023 to Fall 2023

-   Conducted research using FIA sampling methods

-   Cataloged and processed fuel samples

-   Managed and analyzed extensive datasets

**Landscape Assistant**

*Lauman Landscaping \| Roanoke, Virginia* Summer 2022

-   Transported, installed, and maintained various landscaping mediums 

-   Supervised the operation of heavy machinery

-   Fostered a high level of customer service with new and returning customers

**Bar Back and Host**

*Parkway Brewing Company\| Salem, Virginia* Fall 2019 to Summer 2022

-   Directed the training of incoming dishwashers 

-   Organized inventory of the kegerator and merchandise shelves

-   During the pandemic, my duties were expanded to focus on the safety of our customers and compliance with statewide regulations

**Student Technology Intern**

*Roanoke City Public Schools \| Roanoke, Virginia* Spring 2019 to Fall 2019

-   Developed virtual reality lessons for students in summer school classes

-   Cataloged and transported student laptops

-   Installed new programs and applications to the student and faculty computers through source boot controls

## Awards and Acknowledgements

**Eagle Scout**

Completed a commemorative service project for Healing Strides of Virginia requiring the planning, leadership, and supervision of workdays and fundraising events.

**Honors Student**

Student of the honors program offered at Colorado State University. Invited to apply to the program as an incoming freshman and have continued to uphold a high academic standing through the rigorous constructs of the program.

**Volunteer Researcher**

Participated in volunteer fish and macroinvertebrate field research for the Stream Fish Ecology and Conservation Lab in the Department of Fish, Wildlife, and Conservation Biology at CSU.

**Local Conservation Agriculture Collaborator**

Worked with Poudre Valley Community Farms (PVCF) to develop a comprehensive monitoring protocol for bird diversity, nesting success, and soil health. This was completed as a requirement for ESS 501, Principles of Ecosystem Sustainability, and is being implemented and overhauled as my honors thesis project.
